#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create HTML page with Hello World!
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Restart Nginx
sudo service nginx restart
