#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create HTML page with Hello World!
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Redirect
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://x.com/islamhasib953;\n\t}' /etc/nginx/sites-available/default

# 404 custom
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a \\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Add custom header
sudo sed -i '/server_name _;/a \\n\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart
