#!/usr/bin/env bash
#display the number from 0 to 100

cnt=1
while ((cnt <= 100))
do
    if ((cnt % 3 == 0))
    then
        echo "Fizz"
    elif ((cnt % 5 == 0))
    then
        echo "Buzz"
    elif ((cnt % 3 == 0 && cnt % 5 == 0))
    then
        echo "FizzBuzz"
    else
        echo $cnt
    fi
    ((cnt++))
done
