#!/usr/bin/env bash
# print 10 times Best School
for ((num = 1; num <= 10; num++))
do
    if ((num == 9))
    then
        echo "Hi"
    fi
    echo Best School
done
#!/usr/bin/env bash
# print 10 times Best School

cnt=1
while ((cnt <= 10))
do
    echo Best School
    ((cnt++))
    if ((cnt == 10))
    then
        echo "Hi"
    fi
done
