#!/usr/bin/env bash
# print 10 times Best School

cnt=1
while ((cnt <= 10))
do
    if ((cnt == 4))
    then
        echo "bad luck"
    elif ((cnt == 8))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((cnt++))
done
